### ISSUE TITLE
Support for wildcards

### ISSUE THREAD

**Issue by thorstenkampe** [wtjones/PSCode#9]
Trying to replace a custom function with this module, I realized that PSCode doesn't seem to support wildcards (`code *`). Could you implement this?

My old code to alias code
```powershell
if ($IsWindows) {
    function code {
        # support for wildcards via `Get-Item`
        $files = Get-Item -Path @args -ErrorAction SilentlyContinue

        if ($?) {
            Code.exe --reuse-window $files
        }
        else {
            Code.exe --reuse-window @args
        }
    }
}
```

**Comment by wtjones** [comment]
I'm not seeing that vscode has behavior for wildcards. 

In the example, there are two .config files here, but neither command open them:

Vanilla:
```
D:\temp\trizbort>"C:\Program Files (x86)\Microsoft VS Code\code.exe" *.config
```
PSCode:
```
PS D:\temp\trizbort> Invoke-VSCode *.config -verbose
VERBOSE: Launching VSCode with args:
[
    "\"C:\\Program Files (x86)\\Microsoft VS Code\\resources\\app\\out\\cli.js\"",
    "*.config"
]
```

_However_, I did notice this oddity:

Vanilla: This opens the two .config files in the folder:
```
 $files = get-item -path *.config
PS D:\temp\trizbort> & "C:\Program Files (x86)\Microsoft VS Code\code.exe" $files
```

PSCode: This bungles both files into a single string and opens neither:
```
PS D:\temp\trizbort> $files = get-item -path *.config
PS D:\temp\trizbort> Invoke-VSCode $files -verbose
VERBOSE: Launching VSCode with args:
[
    "\"C:\\Program Files (x86)\\Microsoft VS Code\\resources\\app\\out\\cli.js\"",
    "\"D:\\temp\\trizbort\\app.config D:\\temp\\trizbort\\packages.config\""
]
```

It seems to be an issue with how variables are expanded. Is this what you are referring to, or are you also suggesting that it eval the filter with `get-item` before passing to `code.exe`?

**Comment by thorstenkampe** [comment]
In general wildcards are functionality of the shell, not the application. On Windows Cmd and PowerShell support wildcards only for specific commands.

My function wrapper was very basic - it could not distinguish between file arguments and options because there was no need for me to pass options to VSCode. So the logic was: either no argument, or existing files or non-existing files.

It would be up to you to decide whether that way of using VSCode from the command line fits the modul's purpose. Unfortunately I can't tell why `Invoke-VSCode` seems to quote the expanded file arguments or cast them into a string. `$files` is definitely an array.

**Comment by wtjones** [comment]
PSCode is intended to simply pass through the args to code, so I'll have to think on this one. I am open for ways of supplying normal Posh cmdlet behaviors however.

Curious, what is an example use case? I've never launched vs code in this manner (with an array of files).

**Comment by thorstenkampe** [comment]
Well, I rarely do this. But I also rarely open files with VSCode from the command line. Passing wildcard files is just something people do when they are used to "globbing", they are in a shell and there is already a pattern to the files they want to open.

**Comment by wtjones** [comment]
This has been pushed. I basically do a Resolve/Convert path on inputs and them pass them along.

https://www.powershellgallery.com/packages/PSCode/1.0.9
